### ISSUE TITLE
流量标记的例子header匹配少了一个冒号

### ISSUE THREAD

**Issue by liubao68** [apache/servicecomb-docs#248]
https://servicecomb.apache.org/references/java-chassis/zh_CN/references-handlers/governance.html

**Comment by liubao68** [comment]
```
servicecomb:
  matchGroup:
    userLoginAction: |
      matches:
        - apiPath:
            exact: "/login"
          method:
            - POST
        - headers:     -------------这里应该有个冒号
          Authentication: 
            prefix: Basic
      services: helloService
```
