### ISSUE TITLE
应用性能监控指导文档出有一处错误

### ISSUE THREAD

**Issue by YOC19970520** [apache/servicecomb-docs#265]
```
    servicecomb:
        metrics:
            prometheus:
                address: 9696
    ```
此处的address应该为完整的ip+port, 不然会报create http public server failed, bad address : " +address的异常
